##===- runtime/Makefile ------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ..
include $(LFORT_LEVEL)/../../Makefile.config

ifndef NO_RUNTIME_LIBS

PARALLEL_DIRS  := compiler-rt libcxx

endif

include $(LFORT_LEVEL)/Makefile

install::

