##===- lfort/lib/CodeGen/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements the AST -> LLVM code generation library for the 
# C-Language front-end.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../..
LIBRARYNAME := lfortCodeGen

include $(LFORT_LEVEL)/Makefile

