##===- lfort/lib/StaticAnalyzer/Makefile -------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements analyses built on top of source-level CFGs. 
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../..
DIRS := Checkers Frontend
PARALLEL_DIRS := Core

include $(LFORT_LEVEL)/Makefile
