##===- lfort/lib/ASTMatchers/Makefile ----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../..
LIBRARYNAME := lfortASTMatchers

include $(LFORT_LEVEL)/Makefile
