#!/bin/sh

N_STRUCTS=300

# Utility routine to "hand" check vtables.

let i=1;
while [ $i != $N_STRUCTS ]; do
  sed -n "/^__ZTV.*s$i:/,/\.[sg][el]/p" test-lfort.s | grep -v '\.[sg][el]' >test-lfort-ztv
  sed -n "/^__ZTV.*s$i:/,/\.[sg][el]/p" test-gcc.s | grep -v '\.[sg][el]' >test-gcc-ztv
  diff -U3 test-gcc-ztv test-lfort-ztv
  if [ $? != 0 ]; then
     echo "FAIL: s$i vtable"
  else
     echo "PASS: s$i vtable"
  fi
  let i=i+1
done
