##===- lfort/lib/Rewrite/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements code transformation / rewriting facilities.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../../..
LIBRARYNAME := lfortRewriteCore

include $(LFORT_LEVEL)/Makefile

