##===- lfort/lib/StaticAnalyzer/Frontend/Makefile ----------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# Starting point into the static analyzer land for the driver.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../../..
LIBRARYNAME := lfortStaticAnalyzerFrontend

CPP.Flags += -I${PROJ_OBJ_DIR}/../Checkers

include $(LFORT_LEVEL)/Makefile
