##===- unittests/Lex/Makefile ------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL = ../..
TESTNAME = Lex
LINK_COMPONENTS := support mc
USEDLIBS = lfortLex.a lfortBasic.a

include $(LFORT_LEVEL)/unittests/Makefile
