##===- lfort/lib/StaticAnalyzer/Core/Makefile --------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements analyses built on top of source-level CFGs. 
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../../..
LIBRARYNAME := lfortStaticAnalyzerCore

include $(LFORT_LEVEL)/Makefile
