##===- lfort/lib/Sema/Makefile -----------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the semantic analyzer and AST builder library for the 
#  C-Language front-end.
#
##===----------------------------------------------------------------------===##

LFORT_LEVEL := ../..
LIBRARYNAME := lfortSema

include $(LFORT_LEVEL)/Makefile

